version: '3'
services:
  mysql:
    hostname: mysql
    container_name: goalist-db
    restart: always
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: my_goal
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    command: >-
      mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      --skip-character-set-client-handshake
    volumes:
      # DBデータの永続化
      - 'db-data:/var/lib/mysql'
      # 初期設定を読み込む
      - './docker/db/my.conf:/etc/mysql/my.conf'
      # MySQL起動時にDBを作成する
      - './docker/db/init/:/docker-entrypoint-initdb.d'

  app:
    container_name: goalist-app
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    tty: true
    volumes:
      - './src:/go/src/app'
    environment:
      REDIS_HOST: redis
    command: sh ./start_app.sh
      # TODO MySQLが立ち上がっていない状態だと、appコンテナが正しく起動しない

  redis:
    hostname: redis
    container_name: goalist-redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/data'
    command: redis-server --appendonly yes
volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
